"""Tests for POST /api/v1/admin/releases/draft-from-commits.

Endpoint shape (post chunk-2 refactor):
    Request:  {since_sha?: str}
    Response: DraftSuggestionResponse with structured highlights
    Error:    422 ai_unavailable | 422 release_meta_unavailable | 502 llm_error

Source-of-truth for commits is backend/release-meta.json (a build-time
snapshot generated by scripts/generate_release_meta.py). Tests mock the
reader at the SUT's import path: app.api.admin_releases.read_release_meta.
"""
from __future__ import annotations

from datetime import datetime, timezone
from unittest.mock import MagicMock, patch

from fastapi.testclient import TestClient

import app.database as _db_mod
from app.models.release import Release, ReleaseStatus
from app.models.user import User, UserRole
from app.services.auth import create_session, create_user, generate_csrf_token
from app.services.github_commits import Commit
from app.services.release_meta_file import ReleaseMeta, ReleaseMetaUnavailable
from app.services.release_notes_ai import ReleaseNotesSuggestion


# =============================================================================
# Helpers
# =============================================================================

def _make_user(*, email: str, role: UserRole = UserRole.staff) -> User:
    db = _db_mod.SessionLocal()
    try:
        user = create_user(
            db,
            email=email,
            name="Generate Test User",
            password="TestPass123!",
            role=role,
        )
        db.flush()
        db.commit()
        db.refresh(user)
        return user
    finally:
        db.close()


def _make_authenticated_client(app_instance, user: User) -> TestClient:
    db = _db_mod.SessionLocal()
    try:
        u = db.merge(user)
        _, raw_token = create_session(db, u)
        csrf = generate_csrf_token()
        db.commit()
    finally:
        db.close()

    tc = TestClient(app_instance, raise_server_exceptions=True)
    tc.cookies.set("session_token", raw_token)
    tc.cookies.set("csrf_token", csrf)
    tc.headers.update({"X-CSRF-Token": csrf})
    return tc


def _commit(sha: str, subject: str, body: str = "") -> Commit:
    return Commit(
        sha=sha,
        subject=subject,
        author_name="Dev",
        committed_at=datetime(2026, 5, 8, tzinfo=timezone.utc),
        body=body,
    )


def _meta(commits: list[Commit]) -> ReleaseMeta:
    return ReleaseMeta(
        generated_at=datetime(2026, 5, 8, tzinfo=timezone.utc),
        head_sha=commits[0].sha if commits else "",
        branch="test-branch",
        commits=commits,
    )


_ENDPOINT = "/api/v1/admin/releases/draft-from-commits"

_MOCK_AI = "app.api.admin_releases.is_release_notes_ai_available"
_MOCK_READ = "app.api.admin_releases.read_release_meta"
_MOCK_GEN = "app.api.admin_releases.generate_release_notes_suggestion"


# =============================================================================
# Tests
# =============================================================================

def test_local_meta_happy_path(app_instance):
    """Happy path: meta file has 3 commits, 2 user-facing, AI returns structured output."""
    admin = _make_user(email="gen-admin-happy@gen-test.com", role=UserRole.admin)
    tc = _make_authenticated_client(app_instance, admin)

    meta = _meta([
        _commit("aaa111", "feat: smarter drafts"),
        _commit("bbb222", "fix: broken pagination"),
        _commit("ccc333", "chore: update deps"),
    ])
    suggestion = ReleaseNotesSuggestion(
        title="Smarter Drafts and Fixes",
        summary="Drafts are smarter and pagination is fixed.",
        highlights=[
            {"category": "improved", "text": "Smarter drafts"},
            {"category": "fixed", "text": "Fixed pagination"},
        ],
        low_confidence=False,
    )

    with (
        patch(_MOCK_AI, return_value=True),
        patch(_MOCK_READ, return_value=meta),
        patch(_MOCK_GEN, return_value=suggestion),
    ):
        res = tc.post(_ENDPOINT, json={"since_sha": "old111"})

    assert res.status_code == 200
    data = res.json()
    assert data["title_suggestion"] == "Smarter Drafts and Fixes"
    assert data["summary_suggestion"] == "Drafts are smarter and pagination is fixed."
    assert data["highlights_suggestion"] == [
        {"category": "improved", "text": "Smarter drafts"},
        {"category": "fixed", "text": "Fixed pagination"},
    ]
    assert data["commit_count"] == 2
    assert data["commit_sha_at_release"] == "aaa111"
    assert data["generated_from"] == "local_meta"
    assert data["low_confidence"] is False


def test_no_user_facing_commits_returns_zero_count(app_instance):
    """All commits filtered out → 200 with empty suggestion fields, AI not called."""
    admin = _make_user(email="gen-admin-zero@gen-test.com", role=UserRole.admin)
    tc = _make_authenticated_client(app_instance, admin)

    meta = _meta([
        _commit("ddd444", "chore: update ci"),
        _commit("eee555", "refactor: clean up"),
    ])

    with (
        patch(_MOCK_AI, return_value=True),
        patch(_MOCK_READ, return_value=meta),
        patch(_MOCK_GEN) as mock_gen,
    ):
        res = tc.post(_ENDPOINT, json={"since_sha": "abc"})

    assert res.status_code == 200
    data = res.json()
    assert data["commit_count"] == 0
    assert data["title_suggestion"] == ""
    assert data["summary_suggestion"] == ""
    assert data["highlights_suggestion"] == []
    assert data["generated_from"] == "local_meta"
    # SHA still advances to the most-recent fetched commit.
    assert data["commit_sha_at_release"] == "ddd444"
    mock_gen.assert_not_called()


def test_user_facing_opt_in_token_includes_otherwise_excluded_commit(app_instance):
    """A commit with a chore: prefix but `[user-facing]` in body is included."""
    admin = _make_user(email="gen-admin-optin@gen-test.com", role=UserRole.admin)
    tc = _make_authenticated_client(app_instance, admin)

    meta = _meta([
        _commit("opt111", "chore: bump groq sdk", body="[user-facing] enables faster generation"),
        _commit("non222", "chore: cleanup pyproject"),
    ])
    suggestion = ReleaseNotesSuggestion(
        title="Faster generation",
        summary="Release notes generate faster now.",
        highlights=[{"category": "improved", "text": "Generation is faster"}],
        low_confidence=False,
    )

    with (
        patch(_MOCK_AI, return_value=True),
        patch(_MOCK_READ, return_value=meta),
        patch(_MOCK_GEN, return_value=suggestion),
    ):
        res = tc.post(_ENDPOINT, json={"since_sha": "old"})

    assert res.status_code == 200
    data = res.json()
    assert data["commit_count"] == 1
    assert data["commit_sha_at_release"] == "opt111"


def test_default_since_sha_uses_last_published(app_instance):
    """When since_sha is omitted, endpoint uses the last published release's commit_sha."""
    admin = _make_user(email="gen-admin-sha@gen-test.com", role=UserRole.admin)

    expected_sha = "zzz999_local_meta"
    db = _db_mod.SessionLocal()
    try:
        rel = Release(
            title="Gen SHA Boundary Release",
            body=None,
            summary="Boundary helper",
            highlights=[{"category": "fixed", "text": "Boundary"}],
            status=ReleaseStatus.published,
            created_by_id=admin.id,
            commit_sha_at_release=expected_sha,
            # Far-future to win the latest-published race in shared DB.
            published_at=datetime(2099, 6, 1, tzinfo=timezone.utc),
        )
        db.add(rel)
        db.commit()
    finally:
        db.close()

    tc = _make_authenticated_client(app_instance, admin)

    meta = _meta([_commit("fff666", "feat: default sha test")])
    suggestion = ReleaseNotesSuggestion(
        title="Default SHA Test",
        summary="A new feature",
        highlights=[{"category": "new", "text": "New feature"}],
        low_confidence=False,
    )
    mock_read = MagicMock(return_value=meta)

    with (
        patch(_MOCK_AI, return_value=True),
        patch(_MOCK_READ, mock_read),
        patch(_MOCK_GEN, return_value=suggestion),
    ):
        # Empty body → since_sha falls back to last published release's SHA.
        res = tc.post(_ENDPOINT, json={})

    assert res.status_code == 200
    # Cleanup: backdate so this release doesn't pollute downstream tests.
    db = _db_mod.SessionLocal()
    try:
        row = db.query(Release).filter_by(commit_sha_at_release=expected_sha).one()
        row.published_at = datetime(2020, 1, 1, tzinfo=timezone.utc)
        db.commit()
    finally:
        db.close()


def test_meta_file_unavailable_returns_422(app_instance):
    """If release-meta.json is missing/unreadable, return 422 release_meta_unavailable."""
    admin = _make_user(email="gen-admin-no-meta@gen-test.com", role=UserRole.admin)
    tc = _make_authenticated_client(app_instance, admin)

    with (
        patch(_MOCK_AI, return_value=True),
        patch(_MOCK_READ, side_effect=ReleaseMetaUnavailable("file missing")),
    ):
        res = tc.post(_ENDPOINT, json={})

    assert res.status_code == 422
    assert res.json()["detail"] == "release_meta_unavailable"


def test_ai_unconfigured_returns_422(app_instance):
    """No LLM provider configured → 422 ai_unavailable, meta file is not even read."""
    admin = _make_user(email="gen-admin-ai-cfg@gen-test.com", role=UserRole.admin)
    tc = _make_authenticated_client(app_instance, admin)

    with (
        patch(_MOCK_AI, return_value=False),
        patch(_MOCK_READ) as mock_read,
    ):
        res = tc.post(_ENDPOINT, json={})

    assert res.status_code == 422
    assert res.json()["detail"] == "ai_unavailable"
    # AI gate fires first — no point reading the meta file.
    mock_read.assert_not_called()


def test_llm_failure_returns_502(app_instance):
    """LLMError from the underlying client → 502 with llm_error detail."""
    from app.services.llm_client import LLMError

    admin = _make_user(email="gen-admin-502llm@gen-test.com", role=UserRole.admin)
    tc = _make_authenticated_client(app_instance, admin)

    meta = _meta([_commit("xxx111", "feat: thing")])

    with (
        patch(_MOCK_AI, return_value=True),
        patch(_MOCK_READ, return_value=meta),
        patch(_MOCK_GEN, side_effect=LLMError("quota exceeded")),
    ):
        res = tc.post(_ENDPOINT, json={"since_sha": "abc"})

    assert res.status_code == 502
    assert "llm_error" in res.json()["detail"]


def test_low_confidence_passes_through(app_instance):
    """low_confidence=True from the AI is reflected in the response."""
    admin = _make_user(email="gen-admin-lowconf@gen-test.com", role=UserRole.admin)
    tc = _make_authenticated_client(app_instance, admin)

    meta = _meta([_commit("aaa", "feat: x")])
    suggestion = ReleaseNotesSuggestion(
        title="Updates on today",
        summary="AI couldn't structure the response.",
        highlights=[],
        low_confidence=True,
    )

    with (
        patch(_MOCK_AI, return_value=True),
        patch(_MOCK_READ, return_value=meta),
        patch(_MOCK_GEN, return_value=suggestion),
    ):
        res = tc.post(_ENDPOINT, json={"since_sha": "old"})

    assert res.status_code == 200
    assert res.json()["low_confidence"] is True


def test_staff_forbidden(app_instance):
    """Staff (non-admin) user gets 403."""
    staff = _make_user(email="gen-staff-403@gen-test.com", role=UserRole.staff)
    tc = _make_authenticated_client(app_instance, staff)

    res = tc.post(_ENDPOINT, json={})

    assert res.status_code == 403


def test_unauthenticated_returns_401_or_403(client):
    """Unauthenticated POST returns 401 or 403 (CSRF fires first)."""
    res = client.post(_ENDPOINT, json={})
    assert res.status_code in (401, 403)


def test_zero_commits_in_meta_returns_zero_count(app_instance):
    """If the meta file is present but has zero commits matching the boundary,
    returns 200 with commit_count=0 and commit_sha_at_release=None."""
    admin = _make_user(email="gen-admin-empty-meta@gen-test.com", role=UserRole.admin)
    tc = _make_authenticated_client(app_instance, admin)

    meta = _meta([])

    with (
        patch(_MOCK_AI, return_value=True),
        patch(_MOCK_READ, return_value=meta),
        patch(_MOCK_GEN) as mock_gen,
    ):
        res = tc.post(_ENDPOINT, json={})

    assert res.status_code == 200
    data = res.json()
    assert data["commit_count"] == 0
    assert data["commit_sha_at_release"] is None
    assert data["generated_from"] == "local_meta"
    mock_gen.assert_not_called()
