"""
Draft feedback retrieval service.

Mirrors ``KnowledgeService``'s shape — stateless retrieval + prompt
formatting — but reads *implicit* signals Jane has been producing as she
works (approvals, edits, saved messages, rejection reasons) instead of
the manually-authored knowledge base.

These signals are injected into the draft-generation prompt as in-context
examples and anti-patterns. No new tables, no embeddings — just a smarter
prompt builder reading data that's already in the DB.

Retrieval strategy:
  Positive examples — recent approved DraftResponse bodies in the same
    category. The model treats these as voice/style references.
  Curated examples — recent saved EmailMessages (outbound, in the same
    category). These are Jane's explicit "this was a good one" signal,
    weighted higher than plain approvals.
  Negative patterns — recent rejection_reason values in the same category.
    Surface as "issues to avoid", not as full body text.

Hard guards (R1-R8 in the iteration's risk register):
  - Skip threads that have any escalation containing the canonical PII
    phrase "sensitive client data" (emails.py comment is the source of
    truth for that phrase). PII leakage is the highest-impact risk.
  - Saved messages: outbound only — Jane saves inbound client messages
    too, but those are NOT examples of good drafts.
  - Approved drafts: strict status filter (DraftStatus.approved). Skip
    edited/rejected drafts that share the same thread.
  - Rejection reasons: skip the auto-generated "Regenerated by staff"
    placeholder noise.
  - Per-section character cap (_PER_EXAMPLE_CHARS) per individual example
    and total-block cap (_BLOCK_CHARS) prevent prompt bloat.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime
from typing import Final

from sqlalchemy import exists, select
from sqlalchemy.orm import Session

from app.models.email import (
    DraftResponse,
    DraftStatus,
    EmailMessage,
    EmailThread,
    MessageDirection,
)
from app.models.escalation import Escalation
from app.models.user import User
from app.services.categorizer import wrap_user_content
from app.utils.sanitize import strip_html

logger = logging.getLogger(__name__)

# Per-example text cap. Keeps any single example from dominating the prompt
# and bounds the total block size even if the row's body_text is huge.
_PER_EXAMPLE_CHARS: Final[int] = 400

# Total cap per block (positives, curated, negatives). With limit=3 examples
# at 400 chars each + delimiters, ~1500 is the natural ceiling.
_BLOCK_CHARS: Final[int] = 1500

# PII phrase that marks an escalation as PII-flagged. Matches the comment in
# api/emails.py:1335 ("sensitive client data"). Threads with any escalation
# whose reason contains this phrase are excluded from feedback retrieval.
_PII_PHRASE: Final[str] = "sensitive client data"

# Placeholder rejection reason written by the regenerate endpoint
# (drafts.py:691). Filtered out because it's automation noise, not feedback.
_REGENERATE_PLACEHOLDER: Final[str] = "Regenerated by staff"


# Maximum subject length surfaced in the UI / prompt. Subjects can be up to
# 998 chars per RFC 5322 but real emails are typically <100. Cap defensively.
_SUBJECT_CHARS: Final[int] = 80


@dataclass(frozen=True)
class FeedbackExample:
    """A single positive feedback example (approved draft or saved message).

    Fields beyond ``body`` and ``occurred_at`` enrich the UI and the prompt
    label without inflating the example body itself. ``tone`` flows into both
    the UI (rendered as a chip) and the prompt label so Claude treats it as
    a steering signal. ``subject`` and ``actor_name`` are UI-only — they
    help Jane recognize the example without burdening the prompt with
    metadata the model can't act on.
    """
    source: str  # "approved" | "saved"
    body: str
    occurred_at: datetime
    tone: str | None  # thread.suggested_reply_tone when the draft/message landed
    subject: str | None  # truncated thread subject — UI context only
    actor_name: str | None  # who approved (drafts) or saved (messages)


@dataclass(frozen=True)
class FeedbackNegative:
    """A single negative-pattern example (rejection reason).

    Includes the same enrichment fields as ``FeedbackExample`` so the UI can
    show why a particular draft was rejected (subject) and what tone was
    being attempted (tone) — both useful when Jane is reviewing whether the
    issue would still apply to her current draft.
    """
    reason: str
    occurred_at: datetime
    tone: str | None
    subject: str | None
    actor_name: str | None  # who rejected


class FeedbackRetrievalService:
    """
    Stateless retrieval service for implicit-feedback signals.

    Instantiate once and reuse — same pattern as KnowledgeService.
    """

    def get_positive_examples(
        self,
        db: Session,
        category: str,
        limit: int = 3,
    ) -> list[FeedbackExample]:
        """
        Return the most recent approved drafts in the given category.

        Strictly DraftStatus.approved (not "edited" or "sent" — sent drafts
        were once approved, but we use ``approved`` as the cleanest snapshot
        of "draft a human signed off on without further edits needed"). The
        ``sent`` status is a later transition driven by the send pipeline,
        not an additional signal of quality.
        """
        stmt = (
            select(DraftResponse, EmailThread, User)
            .join(EmailThread, DraftResponse.thread_id == EmailThread.id)
            .outerjoin(User, DraftResponse.reviewed_by_id == User.id)
            .where(
                DraftResponse.status == DraftStatus.approved,
                EmailThread.category == category,
                ~_pii_thread_subquery(EmailThread.id),
            )
            .order_by(DraftResponse.reviewed_at.desc().nulls_last())
            .limit(limit)
        )
        rows = db.execute(stmt).all()
        return [
            FeedbackExample(
                source="approved",
                body=_truncate(draft.body_text),
                occurred_at=draft.reviewed_at or draft.created_at,
                tone=thread.suggested_reply_tone,
                subject=_truncate_subject(thread.subject),
                actor_name=user.name if user is not None else None,
            )
            for (draft, thread, user) in rows
        ]

    def get_curated_examples(
        self,
        db: Session,
        category: str,
        limit: int = 3,
    ) -> list[FeedbackExample]:
        """
        Return the most recent saved *outbound* messages in the given category.

        Outbound-only is the critical filter — Jane saves inbound client
        messages frequently (they're reference material for ongoing work),
        but those are emphatically NOT examples of good drafts. Filtering
        to direction = outbound restricts the set to messages the firm
        actually authored.
        """
        stmt = (
            select(EmailMessage, EmailThread, User)
            .join(EmailThread, EmailMessage.thread_id == EmailThread.id)
            .outerjoin(User, EmailMessage.saved_by_id == User.id)
            .where(
                EmailMessage.is_saved == True,  # noqa: E712
                EmailMessage.direction == MessageDirection.outbound,
                EmailThread.category == category,
                ~_pii_thread_subquery(EmailThread.id),
            )
            .order_by(EmailMessage.saved_at.desc().nulls_last())
            .limit(limit)
        )
        rows = db.execute(stmt).all()
        return [
            FeedbackExample(
                source="saved",
                body=_truncate(_message_body_text(msg)),
                occurred_at=msg.saved_at or msg.received_at,
                tone=thread.suggested_reply_tone,
                subject=_truncate_subject(thread.subject),
                actor_name=user.name if user is not None else None,
            )
            for (msg, thread, user) in rows
        ]

    def get_negative_patterns(
        self,
        db: Session,
        category: str,
        limit: int = 3,
    ) -> list[FeedbackNegative]:
        """
        Return the most recent rejection reasons in the given category.

        Excludes the auto-generated placeholder set by the regenerate
        endpoint (drafts.py:691) — that's automation noise, not Jane's
        feedback. Real rejections have a Jane-authored reason.
        """
        stmt = (
            select(DraftResponse, EmailThread, User)
            .join(EmailThread, DraftResponse.thread_id == EmailThread.id)
            .outerjoin(User, DraftResponse.reviewed_by_id == User.id)
            .where(
                DraftResponse.status == DraftStatus.rejected,
                DraftResponse.rejection_reason.isnot(None),
                DraftResponse.rejection_reason != _REGENERATE_PLACEHOLDER,
                EmailThread.category == category,
                ~_pii_thread_subquery(EmailThread.id),
            )
            .order_by(DraftResponse.reviewed_at.desc().nulls_last())
            .limit(limit)
        )
        rows = db.execute(stmt).all()
        return [
            FeedbackNegative(
                reason=_one_line(draft.rejection_reason or ""),
                occurred_at=draft.reviewed_at or draft.created_at,
                tone=thread.suggested_reply_tone,
                subject=_truncate_subject(thread.subject),
                actor_name=user.name if user is not None else None,
            )
            for (draft, thread, user) in rows
        ]

    def format_examples(
        self,
        positive: list[FeedbackExample],
        curated: list[FeedbackExample],
    ) -> str:
        """
        Render positive + curated examples as a prompt block.

        Curated examples render first (Jane's explicit save is a stronger
        signal than implicit approval). Returns "" when both lists are
        empty so the prompt template can conditionally include the block.
        """
        # Curated first (stronger signal), then approvals, deduped by body
        # to avoid showing the same text twice if a saved message exactly
        # matches a recently-approved draft.
        merged: list[FeedbackExample] = []
        seen_bodies: set[str] = set()
        for ex in curated + positive:
            key = ex.body.strip()
            if key in seen_bodies:
                continue
            seen_bodies.add(key)
            merged.append(ex)

        if not merged:
            return ""

        lines = [
            "PAST EXAMPLES (responses we've sent for similar emails — match this voice):",
        ]
        running = 0
        for ex in merged:
            label = "SAVED" if ex.source == "saved" else "APPROVED"
            timestamp = ex.occurred_at.strftime("%Y-%m-%d")
            # Tone goes in the prompt label so Claude can latch onto it as
            # a steering signal — tone is a primary control knob for
            # response style. Subject and actor stay out of the prompt
            # (UI-only — they help humans, not the model).
            tone_token = f" · {ex.tone} tone" if ex.tone else ""
            # wrap_user_content prevents past drafts from injecting
            # instructions back into the prompt (T2.7 — same defense the
            # thread formatter uses).
            safe_body = wrap_user_content(strip_html(ex.body))
            entry = f"---\n[{label}{tone_token} · {timestamp}]\n{safe_body}"
            if running + len(entry) > _BLOCK_CHARS:
                break
            lines.append(entry)
            running += len(entry)
        lines.append("---")
        return "\n".join(lines)

    def format_negatives(self, negatives: list[FeedbackNegative]) -> str:
        """
        Render rejection reasons as a prompt block. Empty string when
        the list is empty so the template can conditionally include it.
        """
        if not negatives:
            return ""

        lines = [
            "COMMON ISSUES TO AVOID (past drafts in this category were rejected because):",
        ]
        running = 0
        for neg in negatives:
            # Tone goes in the negative label too — "the rejected draft
            # was attempted in {tone} tone" gives Claude an extra dimension
            # to steer away from (e.g. "professional tone got rejected as
            # too formal" carries different weight than the bare reason).
            tone_token = f" ({neg.tone} tone)" if neg.tone else ""
            # Reasons are short and not user-content (Jane authored them
            # against her own staff), but wrap defensively all the same.
            safe = wrap_user_content(_one_line(neg.reason))
            entry = f"- {safe}{tone_token}"
            if running + len(entry) > _BLOCK_CHARS:
                break
            lines.append(entry)
            running += len(entry)
        return "\n".join(lines)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _pii_thread_subquery(thread_id_col):
    """
    Correlated EXISTS: true if the thread has any escalation whose reason
    contains the canonical PII phrase. Used with NOT-EXISTS (~) to filter
    PII threads out of every retrieval query.
    """
    return exists().where(
        Escalation.thread_id == thread_id_col,
        Escalation.reason.ilike(f"%{_PII_PHRASE}%"),
    )


def _truncate(text: str | None) -> str:
    if not text:
        return ""
    text = text.strip()
    if len(text) <= _PER_EXAMPLE_CHARS:
        return text
    return text[:_PER_EXAMPLE_CHARS].rstrip() + "…"


def _one_line(text: str) -> str:
    """Collapse a rejection reason to a single line for compact display."""
    return " ".join(text.split())[:_PER_EXAMPLE_CHARS]


def _truncate_subject(subject: str | None) -> str | None:
    """Trim subject to ``_SUBJECT_CHARS`` keeping the leading portion."""
    if not subject:
        return None
    subject = subject.strip()
    if len(subject) <= _SUBJECT_CHARS:
        return subject
    return subject[:_SUBJECT_CHARS].rstrip() + "…"


def _message_body_text(msg: EmailMessage) -> str:
    """Prefer plain text; fall back to HTML-stripped body."""
    body = (msg.body_text or "").strip()
    if not body and msg.body_html:
        body = strip_html(msg.body_html).strip()
    return body


# ── Module-level singleton ─────────────────────────────────────────────────────

_feedback_service: FeedbackRetrievalService | None = None


def get_feedback_service() -> FeedbackRetrievalService:
    global _feedback_service
    if _feedback_service is None:
        _feedback_service = FeedbackRetrievalService()
    return _feedback_service
