"""
Signature resolution + application — the send-time half of per-user signatures.

Since 018, signatures are a SEND-time concern, not a generation-time one:
drafts are generated by the background poller, where the eventual sender is
unknown. Resolution chain:

    Human sends (reply or compose)  →  sender's personal signature
                                       └─ none set → company signature
    T1 auto-send (no human)         →  company signature

`apply_signature` also handles the transition from the pre-018 world, where
the global signature was baked into draft bodies at generation: any trailing
block that byte-matches a *known* signature (the one being appended, the
company block, or the preserved legacy block) is stripped before appending —
so old drafts can't end up double-signed. Matching is exact-suffix only;
staff-typed closings that merely resemble a signature are never touched.
"""
from __future__ import annotations

from sqlalchemy.orm import Session

from app.models.user import User
from app.services import system_settings as ss


def company_signature(db: Session) -> str:
    """The firm-level signature block ("" if unset)."""
    return (ss.get_setting(db, ss.COMPANY_SIGNATURE) or "").strip()


def signature_for_sender(db: Session, user: User | None) -> str:
    """
    Resolve the signature for whoever is sending.

    user=None means there is no human sender (T1 auto-send) → company block.
    A user without a personal signature falls back to the company block.
    """
    if user is not None:
        personal = (user.signature or "").strip()
        if personal:
            return personal
    return company_signature(db)


def apply_signature(db: Session, body: str, signature: str) -> str:
    """
    Return `body` ending with exactly one `signature` block.

    Strips any trailing known-signature block first (idempotent — re-sending
    a body that already ends with the right signature won't double it; a
    legacy-baked or differently-signed body gets stripped and re-signed).
    """
    known = {
        s for s in (
            signature,
            company_signature(db),
            (ss.get_setting(db, ss.LEGACY_DRAFT_SIGNATURE) or "").strip(),
        ) if s
    }

    stripped = body.rstrip()
    # Loop until no known block remains at the tail — handles the (unlikely)
    # stacked case of a legacy block followed by another known block.
    changed = True
    while changed:
        changed = False
        for candidate in known:
            if stripped.endswith(candidate):
                stripped = stripped[: -len(candidate)].rstrip()
                changed = True

    if not signature:
        return stripped
    return f"{stripped}\n\n{signature}"
