"""per-user signatures + company signature

Revision ID: 018
Revises: 017
Create Date: 2026-06-04

Per-user signatures (2026-06-04 decision):
- `users.signature` (nullable TEXT) — each user's personal signature, appended
  at SEND time by whoever clicks Send. (Signatures can no longer be baked at
  generation time: drafts are generated by the background poller, where the
  eventual sender is unknown.)
- The old global `draft_signature` (Jane's personal signature, seeded in 017)
  migrates INTO Jane's user row so her experience is unchanged.
- `company_signature` replaces it in system_settings: the firm-level block
  used by T1 auto-send (no human sender) and as the fallback for users who
  haven't set a personal signature. Seeded with the firm portion of the 017
  block (name/address/contact — no personal lines).
- `legacy_draft_signature` preserves the exact 017 text so the send path can
  strip it from old drafts that still have it baked into the body
  (strip-and-replace transition, self-heals as old drafts drain).

All idempotent (ON CONFLICT DO NOTHING / WHERE guards) — safe to re-run.
"""
import sqlalchemy as sa
from alembic import op

revision = "018"
down_revision = "017"
branch_labels = None
depends_on = None

# Jane's account in production. Mirrors 017's approach of baking the known
# production value into the migration — deterministic, no app-config import.
_JANE_EMAIL = "jane@schilcpa.com"

_COMPANY_SIGNATURE = """Schilmoeller & Schoenfield, PC
3131 Eastside Street, Suite 430
Houston, Texas  77098

Office:  (713) 527-9281 Ext 1
Fax: (346) 415-6337"""


def upgrade() -> None:
    op.add_column("users", sa.Column("signature", sa.Text(), nullable=True))

    # 1. Preserve the legacy global signature for send-time strip matching.
    op.execute(
        """
        INSERT INTO system_settings (key, value, updated_at)
        SELECT 'legacy_draft_signature', value, now()
        FROM system_settings WHERE key = 'draft_signature'
        ON CONFLICT (key) DO NOTHING
        """
    )

    # 2. Move it into Jane's user row (her sends keep the exact same signature).
    op.execute(
        f"""
        UPDATE users
        SET signature = (SELECT value FROM system_settings WHERE key = 'draft_signature')
        WHERE email = '{_JANE_EMAIL}'
          AND signature IS NULL
          AND EXISTS (SELECT 1 FROM system_settings WHERE key = 'draft_signature')
        """
    )

    # 3. Seed the firm-level company signature (T1 auto-send + fallback).
    op.execute(
        f"""
        INSERT INTO system_settings (key, value, updated_at)
        VALUES ('company_signature', $sig${_COMPANY_SIGNATURE}$sig$, now())
        ON CONFLICT (key) DO NOTHING
        """
    )

    # 4. Retire the old key — everything now reads company_signature or the user row.
    op.execute("DELETE FROM system_settings WHERE key = 'draft_signature'")


def downgrade() -> None:
    # Restore the old global key from the preserved legacy copy.
    op.execute(
        """
        INSERT INTO system_settings (key, value, updated_at)
        SELECT 'draft_signature', value, now()
        FROM system_settings WHERE key = 'legacy_draft_signature'
        ON CONFLICT (key) DO NOTHING
        """
    )
    op.execute(
        "DELETE FROM system_settings WHERE key IN ('company_signature', 'legacy_draft_signature')"
    )
    op.drop_column("users", "signature")
